### ISSUE TITLE
ROVER PASSWORD ERROR

### ISSUE THREAD

**Issue by obedmacallums** [goblimey/ntripcaster#5]
Hello,

I defined the mount poin at sourcetable.dat, for example:
STR;uk_leatherhead;Leatherhead;RTCM 3.0;;;;;GBR;51.29;-0.32;1;0;sNTRIP;none;N;N;0;;

when I define users and passwords at ntripcaster.conf like:
/uk_leatherhead:user1:password1,user2:password2

The rovers device can not conect with any password, the server says: 

Kicking unknown 10 [192.168.0.101] [Not authorized], connected for 0 seconds

The password for base devices does work correctly

are you notice that? is there a solution for that?

Thank you very much

**Comment by goblimey** [comment]
Your configuration looks sensible, so it should work.

However, user names and passwords can be difficult, especially when you have to configure them into the rover using some weird user interface.  

Can you persuade the rover to show you the password as you type it in?  I find that helps me get it right.

I also find it best to start off by setting up a very simple user and password (something like user "a" and password "secret") and see if that works.  That gives you confidence that the mechanism is working properly.  Then I remove that account and set up another with a more complicated setting.

Note that each time you edit the ntripcaster.conf, you need to restart the caster so that it sees the change.

Case matters in the password - X and x are different, for example.   (but you knew that, didn't you?)

**Comment by obedmacallums** [comment]
Thanks for your respond.

Im sure than I put the correct credentials, it acept me just when I dont set any password in an specific mount point.

That happend exacty with others repositories from BGK company, will it be a restriction? because it is not a pay version

**Comment by goblimey** [comment]
No, I'm using the free BKG caster.  My rovers can only connect if they supply the correct user name and password.  Base stations can connect using any user name, but they must give the correct password. 

Could you please send me an email via the contacts page on https://goblimey.com/ so that I have your email address?  I will set up a mount point for you on my caster and we will see what happens when you connect to that.

**Comment by obedmacallums** [comment]
Hello Simon, my name is Obed, and my email is obedmacallums@gmail.com

You was right, there is not a problem with your code, it was my ntrip client app, but when I tried directly with a Gnss device everything was ok, I was used ntrip checker android app as client and I don’t know why but does not work with this app:

https://play.google.com/store/apps/details?id=droid.navmatix.ntriptool&pcampaignid=web_share

Thanks for your support, I’m working a lot with Gnss, it’s interesting know that another people work with Gnss projects too

**Comment by goblimey** [comment]
Another happy customer.
